### PR TITLE
Initial commit: Devienne Oboe Sonata No. 5 in D minor, 1st movement

### PR DESCRIPTION
**Pull request by jeremyvisser**
Typeset manually, sourced from a 1798 publication by Sieber in the public domain.

The score is largely faithfully transcribed. Inconsistencies in the original
have been preserved where possible.  For example, the staccato markings are
quite sporadic, where similar sounding phrases have different markings.

The main area of divergence from the original is note beaming and spacing.
The original layout appears to have been optimised for space conservation.
Instead, I have chosen a more readable option. As such, this engraving is
five pages long compared to the original's three.

Please note that I have not assigned an ID to the piece yet, so my pull request contains `Mutopia-0000/00/00-00`. It's unclear from existing documentation how to properly pick a new ID, so I'd appreciate either you assigning one or telling me how I can assign one myself.

### CODE REVIEW

**Comment by glenl** [comment]
You may have missed a discussion about publishing issues in the prep pull request (#985). There is no problem with the piece itself, it is with the naming forced by your use of `\bookOutputName` which causes a number of things to happen that are contrary to how we traditionally publish scores and part-scores.

**The fix:** there would be no change the parts themselves (`\oboe\ and `\bassoon`) but the following would be done,

 1. Move `\header`, `global`, `\bassoon` and `\oboe` code to a new file named `common.ly`.
 2. The `\book` section for score would be moved to a file named 'Sonata5-1-Allegro.ly`.
 3. The `\book` section for the Oboe part moved to `parts/Sonata5-1-Allegro-oboe.ly`.
 4. Similar for the bassoon.

All scores would `\include` the `common.ly` file. The parts scores will be moved to a new folder called `parts` and the `bookOutputName` would be commented out. (a subtitle could be added to denote that they are part scores.) The final layout under `O71/Sonata5-1-Allegro/` would look like,
```bash
Sonata5-1-Allegro-lys/Sonata5-1-Allegro.ly
Sonata5-1-Allegro-lys/common.ly
Sonata5-1-Allegro-lys/parts/Sonata5-1-Allegro-oboe.ly
Sonata5-1-Allegro-lys/parts/Sonata5-1-Allegro-bassoon.ly
```
I would be happy to make these changes for you. Please comment here and I will update the prep pull request.

**Comment by jeremyvisser** [comment]
Hi Glen,

Indeed I did miss the memo in #985. Thanks for bringing it to my attention. I'm not that familiar with the Mutopia contribution process, so I'm sorry for the trouble.  :-)

I'm more than happy to make the changes as required. I'll read over your comments in #985 in more detail later this week, and update this pull request with a new commit incorporating your changes.

**Comment by jeremyvisser** [comment]
I believe I have incorporated the things you’ve asked for in f5894c998f4c74d9f2413a6c8666812dec17ccb6. Please take a look.

**Comment by glenl** [comment]
Thanks, @jeremyvisser . The only line I modified was the footer (our date/id).

**Pull request closed without merging**
