### PR TITLE
fix typo in title

### PR DESCRIPTION
**Pull request by markvdb**

### CODE REVIEW

**Comment by glenl** [comment]
The title was taken directly from the cover page of the [source manuscript](http://urn.kb.se/resolve?urn=urn:nbn:se:statensmusikverk-4032).

**Comment by markvdb** [comment]
Yes indeed, hence the fix, going from "8 petitE pièces" to "8 petitES pièces".

**Comment by glenl** [comment]
+1 on this edit.
My apologies. I read the difference completely backwards.

**Comment by dominicus** [comment]
Needs update to _mutopiatitle_ field as well.

**Comment by glenl** [comment]
@markvdb, @dominicus, I'll do these edits as penance.

**Pull request merged**
