### PR TITLE
Add Divertimento K137

### PR DESCRIPTION
**Pull request by rickh94**
Addition of Mozart's Diveritmento in Bb K 137

### CODE REVIEW

**Comment by dominicus** [comment]
@rickh94  Files with _.ily~_ suffix seem to be prior versions.  OK to remove?

**Comment by glenl** [comment]
That is typically an emacs backup file. Should I start a .gitignore file for this?

**Comment by rickh94** [comment]
yes files with a ~ suffix are backups that I missed when I was cleaning out the main directory. they can be ignored or deleted.

**Comment by dominicus** [comment]
Several other editors use the backup-with-tilde method too (JEdit and gedit come to mind).
There's a .gitignore for files under ftp folder.  It covers several common suffixes that result from compiling LP source.  Should be OK to add *~ as a new entry.
I do find myself having to clean these up manually, as our cleaning script doesn't remove these (and maybe it shouldn't)...would be one less thing to do.

**Comment by chrissawer** [comment]
@rickh94 please confirm which Creative Commons license you want to use - [Attribution 4.0](https://creativecommons.org/licenses/by/4.0/) or [Attribution-ShareAlike 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by rickh94** [comment]
I'd like Attribution-ShareAlike 4.0. Should I edit the header fields to reflect that?

**Comment by chrissawer** [comment]
Thanks for confirming. It's ok, I'll update the header field in the merge.

**Pull request merged**
