### PR TITLE
Update bwv791.ly

### PR DESCRIPTION
**Pull request by michaelcchu**
(replace slur with tie for measure 27-28 d-flat note)

### CODE REVIEW

**Comment by fedelibre** [comment]
@michaelcchu What is your source reference? We need it to check if your corrections are fine.

Even though it's not considered mandatory (AFAICS), I would add a `sourceurl` header. Maybe [this one](https://imslp.org/wiki/Sinfonia_in_E-flat_major,_BWV_791_(Bach,_Johann_Sebastian))?

**Comment by michaelcchu** [comment]
@fedelibre Here's my source reference:

Bach-Gesellschaft Ausgabe, Clavierwerke. Band 1 (pp.24-25)
Leipzig: Breitkopf und Härtel, 1853. Plate B.W. III.

https://ks15.imslp.org/files/imglnks/usimg/d/d1/IMSLP00766-BWV0791.pdf
https://imslp.org/wiki/Sinfonia_in_E-flat_major,_BWV_791_(Bach,_Johann_Sebastian)

https://ks15.imslp.org/files/imglnks/usimg/6/64/IMSLP848751-PMLP14344-BGA3.pdf
https://imslp.org/wiki/Bach-Gesellschaft_Ausgabe_(Bach,_Johann_Sebastian)

**Comment by fedelibre** [comment]
Thanks. I've rebased your commit on current master, changed the commit date and message and added the source and sourceurl headers. If you agree, I'll push the following to your branch and then merge the PR:

```
commit 096196e8702e2ded0129003a3eafc5b98e153997 (HEAD -> pr1122)
Author: Michael Chu <michael02chu@gmail.com>
Date:   Mon Jul 8 11:41:54 2024 +0200

    BWV 791: replace slur with tie for measure 27-28

diff --git a/ftp/BachJS/BWV791/bwv791/bwv791.ly b/ftp/BachJS/BWV791/bwv791/bwv791.ly
index 6edb69dd..a0bb3074 100644
--- a/ftp/BachJS/BWV791/bwv791/bwv791.ly
+++ b/ftp/BachJS/BWV791/bwv791/bwv791.ly
@@ -9,7 +9,8 @@
   mutopiaopus = "BWV 791"
   mutopiainstrument = "Harpsichord, Piano"
   style = "Baroque"
-  source = "Unknown"
+  source = "Bach-Gesellschaft Ausgabe 1851-1899"
+  sourceurl = "https://ks15.imslp.org/files/imglnks/usimg/d/d1/IMSLP00766-BWV0791.pdf"
   copyright = "Public Domain"
   maintainer = "Olivier Vermersch"
   maintainerEmail = "olivier.vermersch (at) wanadoo.fr"
@@ -99,8 +100,8 @@ melone =  \relative c'' {
 
   % bars 26-29
   r r8 r16 f bes8. aes16 |
-  g4 ~ g8. aes16 des,4 ( |
-   d8.) c16 c4 ( bes8.) aes16 |
+  g4 ~ g8. aes16 des,4 ~ |
+  des8. c16 c4 ( bes8.) aes16 |
   aes4 ~ aes8. ees16 aes8. bes16 |
 
   % bars 30-33
```

**Comment by michaelcchu** [comment]
Looks good; thanks for your help! You can go ahead with the push & merge.

**Comment by fedelibre** [comment]
I don't know what happend, but something went wrong. Maybe the rebase. I just did:

```
$ git pull -r origin master
remote: Enumerating objects: 100, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 100 (delta 42), reused 42 (delta 42), pack-reused 48
Ricezione degli oggetti: 100% (100/100), 26.08 KiB | 13.04 MiB/s, fatto.
Risoluzione dei delta: 100% (43/43), completato con 39 oggetti locali.
Da github.com:MutopiaProject/MutopiaProject
 * branch              master     -> FETCH_HEAD
   6272a56e..77bbcfcf  master     -> origin/master
warning: skipped previously applied commit eccf78ca
warning: skipped previously applied commit 80e7de8e
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Rebase e aggiornamento di refs/heads/pr1122 eseguiti con successo.
```

and

```
$ git push --force michaelcchu master
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To github.com:michaelcchu/MutopiaProject.git
 + 156979c7...6272a56e master -> master (forced update)
```

I will push the patch separately from this PR.

**Comment by fedelibre** [comment]
Commit b21bc1e402827821f8f5cb7ed607a402d3599d0e

**Pull request closed without merging**
