### PR TITLE
French3

### LINKED ISSUE #546: Add Tchaikovsky P I Opus 39 #16 "Old French Song"
I plan on typesetting this one, new content.
Can you assign this to me?

### PR DESCRIPTION
**Pull request by mapadofu**
#546 Tchaikovsky Op39, Piece 16 "Old French Song"

Closes #546

### CODE REVIEW

**Comment by mapadofu** [comment]
What do I need to do to get this merged?

**Comment by chrissawer** [comment]
If 1948 is the original date of this edition's publication then unfortunately this is too new to be public domain in the US.
http://www.mutopiaproject.org/contribute.html
Is it possible to proof read against another edition which is definitely PD?

**Comment by mapadofu** [comment]
Chris, 
Yes, I'll get to it pretty soon. I haven't been typesetting much lately, but I'll put it on the front of the queue. 

Dave 
----- Original Message -----

**Comment by dominicus** [comment]
@mapadofu
For your consideration, version matching Schirmer 1904:
https://gist.github.com/dominicus/5ddc55d278dcb03f50ee
If acceptable, will you commit to your fork branch to amend the pull request?

**Comment by mapadofu** [comment]
Updated mapadofu/The-Mutopia-Project french3  -- I think that that is all that I needed to do.

**Comment by chrissawer** [comment]
Github is reporting conflicts and 301 files changed.
Can this be fixed on your fork please so I can merge the pull request?
I have built from your fork and the file itself looks ok.
If fixing your fork is not practical let me know and I can merge the file manually.

**Comment by mapadofu** [comment]
Sorry about the sloppy commit (I'm still having problems keeping the github workflow straight).
Dropping this one; posting a cleaner one as a separet pull request.

**Pull request closed without merging**
