### PR TITLE
Add "Herr, nun lässest du deinen Diener in Frieden fahren" by Mendelssohn Bartholdy (MWV60, op. 69 No. 1)

### PR DESCRIPTION
**Pull request by jonathan-scholbach**

### CODE REVIEW

**Comment by glenl** [comment]
First I want to thank you for your contribution. Now I want to explain how you did the exact right thing here but, because of the wrong thing on the previous pull request, it didn't come out right.

The Mendelssohn_MWV60 branch was created properly off the master, then you added and committed the contribution. Unfortunately, the master contained the 13 files waiting for the pull request to be merged so GIT has 14 files in this request. This is how to fix this:

```bash
$ git co Mendelssohn_MWV60
$ git reset --soft HEAD~2
$ git status
$ git add ftp/Mendelssohn-BartholdyF/O69/MWV60/Nunc_dimittis.ly
$ git commit -a
```
The ``reset --soft HEAD~2`` to back out the last 2 commits (in this branch) without deleting files. This should leave you with only your Mendelssohn file in "changes not committed" (since the 13 are committed in the master branch.) Then add and commit the one you want *in this branch*. I *think* this will fix your local repository. Since you have pushed to a public repository, you will have to force a push.
```bash
$ git push --force origin Mendelssohn_MWV60
```

**Comment by jonathan-scholbach** [comment]
Thank you for the detailed instructions and sorry for the confusion I caused in the first place. I hope everything is clean now. Just to make no mistake again (I'm not very familiar with git yet): I have to request a new pull from the Mendelssohn_MWV60 branch now?

**Comment by glenl** [comment]
No. The request shows 1 changed file so it looks good.

**Comment by chrissawer** [comment]
With LilyPond 2.18.2 I get the following errors and no midi output. Could you take a look please?

```
Parsing...
Nunc-dimittis.ly:998:7: error: syntax error, unexpected OUTPUT_DEF_IDENTIFIER
      
      \stafftovoice
Nunc-dimittis.ly:1013:7: error: syntax error, unexpected OUTPUT_DEF_IDENTIFIER
      
      \stafftovoice
Nunc-dimittis.ly:1028:7: error: syntax error, unexpected OUTPUT_DEF_IDENTIFIER
      
      \stafftovoice
Nunc-dimittis.ly:1043:7: error: syntax error, unexpected OUTPUT_DEF_IDENTIFIER
      
      \stafftovoice
Nunc-dimittis.ly:1058:7: error: syntax error, unexpected OUTPUT_DEF_IDENTIFIER
      
      \stafftovoice
```

**Comment by glenl** [comment]
This compiles cleanly with 2.19.48 but with complaints about page counts. Commenting out the paper variables at line 918 still gives a clean 4-page output. I've not done a review between the two outputs and I'm not suggesting this as a fix, just an observation.

The midi output is lovely.

**Comment by chrissawer** [comment]
We can certainly compile with a newer LilyPond if that would fix the problem.
@jonathan-scholbach did you use 2.18 or a newer version?

**Comment by jonathan-scholbach** [comment]
Sorry for my delay in answering and sorry for the error in the first place. I compiled it with LilyPond 2.19.22 with the version statement `\version "2.18.2"`. That gives me no error, but a `Success: compilation successfully completed`. Unfortunately I am unable to find out what's causing the error with 2.18 (I just understand a way too little of LilyPond's different versions to get even a foggy notion of possible sources for that error.)
So I see two possibilities: Either you compile it with 2.19.22 or later or I delete the midi-output part. Option 1 is my preference, so if compiling with a newer version of LP was possible, as @chrissawer mentioned, I would be thankful.

**Comment by chrissawer** [comment]
Compiled fine with LilyPond 2.19.22 - thanks.

**Pull request merged**
