### PR TITLE
Create Gnossienne no_7 in SatieE

### PR DESCRIPTION
**Pull request by 7redi**

### CODE REVIEW

**Comment by chrissawer** [comment]
Unfortunately the 1986 source edition is too new and will not be in the public domain yet.
Is it possible to find an older edition which is PD worldwide, maybe from IMSLP, and proofread against it?
See: http://www.mutopiaproject.org/contribute.html

**Comment by 7redi** [comment]
Sorry about that.

I've done some research to try and understand why the score is public
domain on IMSLP. My understanding is that  the *Erik Satie: Klavierwerke,
Band 1* is an Urtext edition and as such is public domain after 25 years.
Strangely this is not explained in all the excerpts of the edition, but you
can find it here for example :

http://imslp.org/wiki/Descriptions_automatiques_(Satie,_Erik)

I don't know if this complies to Mutopia standards. Maybe have you
encountered this situation before ?

Thanks for your work !

Fred

**Comment by dominicus** [comment]
IMSLP seems to have inconsistent copyright tags for the cited Klemm/Peters edition.
Other pieces in this collection appear [here](http://imslp.org/wiki/Gnossiennes_(Satie,_Erik)#IMSLP237520) coded as Non-PD-US.
I added a note in IMSLP to align.
While there's a PD source for Nos1-6, I couldn't find an alternative one for your typeset of No7.

**Comment by 7redi** [comment]
All-right then. Let me know when IMSLP gets back to you.

**Comment by dominicus** [comment]
IMSLP admins have [replied](http://imslp.org/index.php?title=Special:WikiForum&thread=15855), but this won't change the fact the Klemm/Peters source doesn't meet Mutopia's stricter criteria for sources.
In lieu of an alternative PD source, we can archive the submission and revisit once one becomes available.
If you have an IMSLP account, you can sign up to "Watch" the [corresponding page](http://imslp.org/wiki/Le_Fils_des_%C3%A9toiles_(Satie,_Erik)), so you're notified whenever new sources are added.
You can also reach out to the listed IMSLP users that have published Satie scans to IMSLP.  They may be in a better position to offer tips on where one could search for digitized PD versions of Satie's works.  We keep [a general page](https://github.com/MutopiaProject/MutopiaProject/wiki/Public-domain-sources) of PD sources.

**Comment by 7redi** [comment]
Thanks for the tips. I'll be more careful on PD issues on my following projects.

**Comment by dominicus** [comment]
@7redi thanks for the contribution.
I've parked your submission in #850 pending alternative PD source.

**Pull request closed without merging**
