### PR TITLE
Update BWV600

### PR DESCRIPTION
**Pull request by glenl**
@chrissawer in landscape mode

Closes #971

### CODE REVIEW

**Comment by chrissawer** [comment]
Built with "mupub build" both PDF files are A4 format instead of letter.
Is there a workaround for this or should I build manually for now?

**Comment by metzguar** [comment]
Hi Chris,the reason is probably the line "#(set-default-paper-size "a4" 'landscape)".Unfortunately "landscape" does not seem to work without a size parameter.So unless your build script can handle this and replace "a4" with "letter", I see no other way than build manually.Sorry for that.Regards, UrsChris Sawer <notifications@github.com> hat am 11. April 2018 um 13:55 geschrieben:  Built with "mupub build" both PDF files are A4 format instead of letter. Is there a workaround for this or should I build manually for now?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by glenl** [comment]
These commands also work in this fashion (at least on versions > 2.18),
```
#(set-default-paper-size "a4landscape")
#(set-default-paper-size "letterlandscape")
```
I just tried using this as `-dpapersize=\"letterlandscape\" on 2.18.2 and it performed as expected. I can make an update to our build command that will offer this appending with a `--landscape` modifier. It would be a rather trivial update. In this case we would have to comment out that line in the source file.

We can consider more elaborate mechanisms later but this might be a reasonable fallback.

**Comment by chrissawer** [comment]
I will change the file manually for now and build twice.
Our old java build system did have a "landscape hack" for modifying the file as part of the build process.
It would be nice to have a better solution long term.

**Pull request merged**
