### PR TITLE
New file: scarlatti-k455.ly

### PR DESCRIPTION
**Pull request by ksnortum**
New file: scarlatti-k455.ly.  Requires LilyPond 2.19.19. or newer.

### CODE REVIEW

**Comment by chrissawer** [comment]
What is the source for this contribution please?

**Comment by ksnortum** [comment]
The source is from IMSLP.  It says "Paris: Heugel
<http://imslp.org/wiki/Heugel>, 1972. Plate H. 32,201."


Knute Snortum
(via Gmail)

**Comment by ksnortum** [comment]
If that's not going to work, there is also this one: Montréal: Les Éditions
Outremontaises, 2006.
Copyright:

Creative Commons Attribution Non-commercial 3.0
<http://imslp.org/wiki/IMSLP:Creative_Commons_Attribution_Non-commercial_3.0>


Knute Snortum
(via Gmail)

**Comment by chrissawer** [comment]
Unfortunately the Non-commercial component of that license is not compatible with the licenses we use on Mutopia as we want everything available to be classed as free cultural works.
http://creativecommons.org/freeworks
http://www.mutopiaproject.org/legal.html
http://www.mutopiaproject.org/contribute.html
Is it possible to proof read against another edition which is definitely PD?

**Comment by dominicus** [comment]
http://www.internetculturale.it/opencms/opencms/it/viewItemMag.jsp?case=&id=oai%3A193.206.197.121%3A18%3AVE0049%3AARM0002950

Source: Queen Maria Barbara manuscript (1756) at Biblioteca nazionale Marciana - Venice

Permission to reuse:  http://www.internetculturale.it/opencms/opencms/it/main/chisiamo/uso/

**Comment by chrissawer** [comment]
If the source from @dominicus is acceptable and has been proofread against, let's update the source field and get this published.

**Comment by ksnortum** [comment]
I am having trouble downloading or viewing the the source @dominicus posted.

**Comment by dominicus** [comment]
The viewer fails to load the image for me too, alerts of a server issue.  Other pieces from the same book seems to load, and this one displayed with no issue when I created the link.  I'd say try later...the server may be having issues loading this particular file.  Once you do get it, they have a download button.  Sorry I failed to actually save when I had the chance.

**Comment by ksnortum** [comment]
I have been able to download the source and I will start rewriting the piece soon.

**Comment by ksnortum** [comment]
Rewritten without the aid of the copyrighted source.

**Pull request merged**
