### PR TITLE
Robert Browne Hall's Tenth Regiment March

### PR DESCRIPTION
**Pull request by SarekOfVulcan**
Adding files for R. B. Hall's Tenth Regiment March, also known as "Death or Glory". These parts have been performance-tested. The score was originally set on legal paper at staff-size 12.

I'm sorry if I'm getting this wrong, this is the first time I've tried to do this.

### CODE REVIEW

**Comment by SarekOfVulcan** [comment]
I typeset them from the files at the [IMSLP](http://imslp.org/wiki/Tenth_Regiment_March_(Hall,_Robert_Browne)), if that's useful to know.

**Comment by chrissawer** [comment]
Looks good. I added a mutopiainstrument field.

**Comment by SarekOfVulcan** [comment]
Thanks, @chrissawer -- my only question is, should we make a distinction between brass band and concert/marching/military band, since brass bands generally omit woodwinds?

**Comment by chrissawer** [comment]
@SarekOfVulcan good call, I have changed it to Concert Band, which is also consistent with the Sousa march we have: http://www.mutopiaproject.org/cgibin/piece-info.cgi?id=1643

**Pull request merged**
