### PR TITLE
Quatuor 12 Initial version

### PR DESCRIPTION
**Pull request by sebastien-bugzilla**
Hello
I propose this initial version of Quatuor 12 Op96 of Anton Dvorak.
Feel free to comment.
Sébastien

### CODE REVIEW

**Comment by sebastien-bugzilla** [comment]
Hello
May I have a feedback on what I'm doing ? I've updated Johann Sebastian Bach Cello Suites and I didn't expect that the modifications will be mentioned in this pull request dedicated to Dvorak Quatuor. Is that a problem ? If so, how can I correct it ?
I've also tried to bettered the render (personal point of view, I know) of the score even if I had to write more complex code. Is it something expected ?
I didn't mentioned that it's my first pull request. Any advice is welcome !

**Comment by glenl** [comment]
Sébastien,
Yes, the Dvorak quartet o96 should have been submitted as a separate pull request. The most convenient for our processing is to have a separate branch and pull request for each piece. This pull request should be broken up into BWV 1007, 1008, 1009, 1010, 1011, 1012, and the Dvorak piece.

Was it your intention to submit only the Dvorak piece at this time? Are the Bach pieces in this pull request also ready for submission?

**Comment by sebastien-bugzilla** [comment]
Thank you for your help glenl and happy new year. I understand that I've not worked properly. I didn't create a separate branch for each and I don't know how to revert this. The only option I see is to : 
1 : save a local copy of file I've created.
2 : delete my fork of MutopiaProject and create a new clone.
3 : add 7 new branch for each 7 scores I've modified.
4 : create a pull request for each one.
I don't know what will become this pull request if i delete the fork. I think I will close this pull request now and I hope that will get the message by mail or here...

**Comment by glenl** [comment]
Yes, of course you can do it this way and I'm sure you will be careful with all your files. I think I see how you did this --- you were editing pieces in your repository's master branch and so everything you pushed became part of the pull request. If you have room, I would suggest renaming instead of deleting your repository until you get this sorted.

Take a look at the `git reset --soft` command for another way to get files safely out of a branch without destroying them. In this case, where you've modified your repository master, it might be safer to use the method you've outlined.

I believe if you delete the fork it will automatically delete pull requests from that fork. Don't worry too much about that part of things.

**Pull request closed without merging**
