### PR TITLE
Furelise 1

### PR DESCRIPTION
**Pull request by jeffreyolson**
This version of Fur Elise is an arrangement for guitar duo, based on an earlier version for piano that was already in the repo (Mutopia-2012/12/23-931).  I now see that ID 931 has been updated in 2015, but I doubt that would affect this new arrangement.  FYI, this is my first use of github and my first contribution to Mutopia so I welcome any RTFM pointers I may have missed.  Thank you.

### CODE REVIEW

**Comment by dominicus** [comment]
@jeffreyolson Thank You for the contribution.
 * Our "maintainer" field is also used to credit the arrangement work.  Thus I recommend updating to include the co-arranger "D. Burns and J.J. Olson" so both names are listed in the copyright statement.
 * Please confirm you've obtained agreement from the co-arranger to release this to the public domain.
 * The midi plays well \with { midiInstrument = #"acoustic guitar (nylon)" }  ...optional for you to consider.

**Comment by jeffreyolson** [comment]
Per the attached message, Dennis Burns would prefer to be acknowledged 
in the source file rather than as a co-arranger.  He is also good with 
releasing to public domain.

The midi instrument has been left at "acoustic grand" since, at least on 
my systems,  the nylon guitar sounds too nasal in the upper register 
where this piece starts.

The source date was added, from the previously updated piano edition.

A new commit with these changes has been pushed for your review.

------------------------------------------------------------------------

**Comment by dominicus** [comment]
Excellent.  Thanks again for this nice arrangement.

**Comment by chrissawer** [comment]
Looks good, thanks.
Unfortunately our build scripts couldn't cope with the ASCII art comments following some of the header fields so I have moved them up slightly.

**Pull request merged**
