### PR TITLE
Ulibarri edits to Aguado

### PR DESCRIPTION
**Pull request by pikurasa**
Hi,

I found some errors in the A minor study of the Aguado.

@glenl Maybe you can verify the changes and the styling.

One error I found brings up an important question: "Do we stay faithful to the version we are copying even when there is an obvious error in the original score?"

The error I found is completely illogical: A note cannot both be an open string note and fretted. Therefore, I chose to change it. Otherwise, when it comes to fingerings and differences in opinion, I will not change it.

Also, I want to start adding a URL to where to find the original on the web and page numbers. This makes for easier editing. Glen, how would you like to do this? I defer to you, since you have put in the most work so far.

Thank you!

### CODE REVIEW

**Comment by glenl** [comment]
+1 on these edits (and feeling embarrassed about the c -> b correction in the 13th bar!)

As a novice guitarist I *try* to trust the provided fingerings but I rarely change them in a transcription. If one is completely baffling I would omit it rather than suggest my own. I try to stay true to the original in my transcriptions but don't see a problem with fixing obvious errors if they are annotated in the source.

Regarding URLs, there are a number of choices. One is the simple comment, as you have done, and the other is to put it in the `moreinfo` header field, which will show up when piece information is requested on the site. The obvious problem with URLs is that many aren't permanent. 

More importantly, this is one of those submissions where I could have done a better job with the publishing source rather than listing the text of the on-line source. Could you make this header edit?

source: Schonenberger, Paris. Plate S. 1320
date: ca. 1846

**Comment by pikurasa** [comment]
I made the requested edits as I understood them.

**Comment by pikurasa** [comment]
@glenl I made edits to the g major allegro by Aguado. There was just one courtesy accidental that I did not know how to add (although it reads correctly).

Note: The original, again, had some errors. Notably the G naturals near the end of the score (mm 38 and 46). G sharp makes no sense. I suspect the person who copied these for Aguado made a careless mistake.

Cheers!
I noted everything in the lilypond file.

**Comment by glenl** [comment]
Thanks for the updates.

To make life easier on our publishing process, it would be best to put the last change (https://github.com/MutopiaProject/MutopiaProject/pull/789/commits/52b623a146f28f63336d82d5ecfd35de61278e08) in a separate branch. The only way I know to do this is to back out the last change with a `reset --soft`, re-push the branch with a `--force`, then commit the last change in a new branch. See below.

@chrissawer - If you can make a one-time exception for Devin so he doesn't have to go through the following steps, please note that in a comment on this pull request.

```bash
$ git checkout ulibarri-edits
$ # move HEAD to the last of the a-minor-allegro edits, 'soft' == leave g-major-allegro file
$ git reset --soft 5cb5bf9
$ # Submit changed branch (a force is needed here since you are "re-publishing" a change)
$ git push --force upstream ulibarri-edits
$ git checkou master
$ # submit g-major-allegro change in new branch
$ git checkout -b aguado-fix-g-major-allegro
$ # this command should show the g-major-allegro change
$ git status
$ git commit -a
$ git push upstream aguado-fix-g-major-allegro
```
You will need to create a new pull request for the `g-major-allegro` branch.

**Comment by pikurasa** [comment]
@chrissawer Please let me know if you will pull this as is.

Otherwise, I am willing to fix the error using Glen's recipe. However, I would be more likely to make a mistake trying to follow it since I am not super-fluent in git (much better with music).

I now understand the work flow you want for branches and will correct the way I did this for the future.

Devin

**Comment by chrissawer** [comment]
Happy to take both of these on one pull request.

**Pull request merged**
