### PR TITLE
New file: scarlatti-k491.ly

### PR DESCRIPTION
**Pull request by ksnortum**
New file: scarlatti-k491.ly.  Needs LilyPond v2.19.19 or newer.  Emits four bar check warnings that can be ignored.  (There is no good way to correct this.  It's a bug in LilyPond.)

### CODE REVIEW

**Comment by chrissawer** [comment]
What is the source for this contribution please?

**Comment by ksnortum** [comment]
The source is from IMSLP:  Montréal: Les Éditions Outremontaises, 2013
Copyright:

Creative Commons Attribution-NonCommercial 3.0
<http://imslp.org/wiki/IMSLP:Creative_Commons_Attribution-NonCommercial_3.0>


Knute Snortum
(via Gmail)

**Comment by chrissawer** [comment]
Unfortunately the Non-commercial component of that license is not compatible with the licenses we use on Mutopia as we want everything available to be classed as free cultural works.
http://creativecommons.org/freeworks
http://www.mutopiaproject.org/legal.html
http://www.mutopiaproject.org/contribute.html
Is it possible to proof read against another edition which is definitely PD?

**Comment by dominicus** [comment]
K491:
http://www.internetculturale.it/opencms/opencms/it/viewItemMag.jsp?case=&id=oai%3A193.206.197.121%3A18%3AVE0049%3AARM0001534

Source: Queen Maria Barbara manuscript (1756) at Biblioteca nazionale Marciana - Venice

Permission to reuse: http://www.internetculturale.it/opencms/opencms/it/main/chisiamo/uso/

**Comment by chrissawer** [comment]
If the source from @dominicus is acceptable and has been proofread against, let's update the source field and get this published.

**Comment by ksnortum** [comment]
How much do I have to do things like make the stems up instead of down or make two voices instead of chords?

**Comment by dominicus** [comment]
In general, if the intended articulation relies on voices being split, and to the extent stem direction points to which voice a pitch belongs to, then yes, I'd match these.
Older manuscripts and early plates will sometimes have sections with weird configurations, which are clearly employed to deal with space shortages.  In these cases, OK to favor clarity and readability over trying to match the source.

**Comment by ksnortum** [comment]
I have been able to download the source.  It's very different from my other source, so it may take me some time to repost.

**Comment by ksnortum** [comment]
I rewrote the code without looking at the copyrighted source so that I can have a clear conscience about it.  It should be ready to commit.

**Comment by glenl** [comment]
+1

**Pull request merged**
