### PR TITLE
Prep 909

### PR DESCRIPTION
**Pull request by glenl**
Set for publication after contributor updates.

Closes #909

### CODE REVIEW

**Comment by chrissawer** [comment]
bwv1013_sax.ly - preview and midi don't build for me using "mupub build".
Any ideas?
```
Building preview and midi
GNU LilyPond 2.18.2
Processing `bwv1013_sax.ly'
Parsing...
Interpreting music...
Interpreting music...[8][16][24][32][40][48][48]
Preprocessing graphical objects...
Interpreting music...
Interpreting music...[8][16][24][32][40][48][56][64]
Preprocessing graphical objects...
Interpreting music...
Interpreting music...[8][16][24][32][40]
Preprocessing graphical objects...
Interpreting music...
Interpreting music...[8][16][24][32][40][48][56][64][72]
Preprocessing graphical objects...
MIDI output to `bwv1013_sax.midi'...
MIDI output to `bwv1013_sax-1.midi'...
MIDI output to `bwv1013_sax-2.midi'...
MIDI output to `bwv1013_sax-3.midi'...
Calculating page and line breaks (4 possible page breaks)...[1][2][3][4]
Drawing systems...
Layout output to `bwv1013_sax.preview.svg'...
warning: cannot find SVG font #f
warning: cannot find SVG font #f
/home/centos/.mupub/lycache/2.18.2/lilypond/usr/share/lilypond/current/scm/output-svg.scm:428:30: In procedure string-join in expression (string-join (map # glyphs) "
"):
/home/centos/.mupub/lycache/2.18.2/lilypond/usr/share/lilypond/current/scm/output-svg.scm:428:30: Wrong type (expecting string): #<unspecified>
Traceback (most recent call last):
  File "/usr/bin/mupub", line 9, in <module>
    load_entry_point('mupub==0.5.4', 'console_scripts', 'mupub')()
  File "/usr/lib/python3.4/site-packages/mupub-0.5.4-py3.4.egg/mupub/__main__.py", line 21, in main
  File "/usr/lib/python3.4/site-packages/mupub-0.5.4-py3.4.egg/mupub/cli.py", line 133, in dispatch
  File "/usr/lib/python3.4/site-packages/mupub-0.5.4-py3.4.egg/mupub/commands/build.py", line 206, in main
  File "/usr/lib/python3.4/site-packages/mupub-0.5.4-py3.4.egg/mupub/commands/build.py", line 164, in build
  File "/usr/lib/python3.4/site-packages/mupub-0.5.4-py3.4.egg/mupub/commands/build.py", line 116, in _lily_build
  File "/usr/lib/python3.4/site-packages/mupub-0.5.4-py3.4.egg/mupub/commands/build.py", line 105, in _build_one
  File "/usr/lib/python3.4/site-packages/mupub-0.5.4-py3.4.egg/mupub/commands/build.py", line 84, in _build_preview
  File "/usr/lib64/python3.4/subprocess.py", line 617, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/home/centos/.mupub/lycache/2.18.2/bin/lilypond', '-dno-point-and-click', '-dno-print-pages', '-dpreview', '-dbackend=svg', '-dno-include-book-title-preview', 'bwv1013_sax.ly']' returned non-zero exit status 1
```

**Comment by glenl** [comment]
Duh. I didn't review/update the _sax folder. I'm getting the same error. This is LilyPond crashing with the SVG backend not finding a font but ... it doesn't appear the file is doing anything special with fonts. Doing it as a png works,
```bash
$ lilypond -dno-print-pages -dpreview --format=png bwv1013_sax.ly
```
I might put a flag in mupub to give us a choice when this happens.

More later.

**Comment by glenl** [comment]
Found it: `\markup{\finger ...}` is an incorrect way of using `\finger`.

I replaced instances of `\finger` with `\sans`. This seems to give a good approximation of the original transcription without the preview failure without having to do a major amount of editing. I believe this is now ready to launch.

**Comment by chrissawer** [comment]
Good spot @glenl - thanks for fixing the issue

**Pull request merged**
