### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by fedelibre** [comment]
Looks good to me.
First commit is a little bit confusing since you removed a lot of trailing spaces.. I would have not done it or done it in a separate commit,  to make review easier.

@glenl please check

**Comment by glenl** [comment]
@fedelibre, thanks for the review. I can relate to whitespace diffs --- my emacs write-hook contains a macro to clean trailing whitespace and this often happens to me. Using this command,
```
git diff --ignore-all-space f582063c 1a02c8a9 SilcherF/UntreueM/UntreueM.ly
```
... reveals a slight change to the `arranger` header field as well as `lastupdated`.

@chrissawer,
29 files are changed in this commit, all of which are maintained by Klaus Rettinghaus.
Of these, only 4 files have changes that will result in a difference in the published pdf output:

 - Mendelssohn-BartholdyF/O47/RatundScheiden/RatundScheiden.ly
 - SilcherF/Soldatenbraut/Soldatenbraut.ly
 - VolkmannR/O30/AugenhaltenM/AugenhaltenM.ly
 - SilcherF/UntreueM/UntreueM.ly

One of the remaining 25 files has a fixed typo in a comment, others have changes to a `lastupdated` header field which is ignored by LilyPond as well as Mutopia.

Let me know how you want to proceed on this. I did a quick `mupub check` on all of these files and found only one issue (a version macro set as 2.18 instead of 2.18.0).

**Comment by rettinghaus** [comment]
@fedelibre Sorry for the mess. The different line breaks originally came from different platforms. At best they should be all be LF. 
Perhaps we should add a [.gitattributes](https://git-scm.com/docs/gitattributes) to the project, to deal correctly with CRLF?  What do you think, @chrissawer?
See https://help.github.com/articles/dealing-with-line-endings/

**Comment by fedelibre** [comment]
> I did a quick `mupub check` on all of these files and found only one issue (a version macro set as 2.18 instead of 2.18.0).

It's the first file here:

```
$ git grep '\version "2.18"'
ftp/SchreckG/DergrimmigTod/DergrimmigTod.ly:\version "2.18" 
ftp/TchaikovskyPI/O59/dumka/dumka.ly:\version "2.18"
```

Anyway, this can be fixed later when we'll update the files to the latest LilyPond stable. Let's merge this PR and move on.

**Pull request merged**
