### PR TITLE
added Jesu, meine Freude (BWV227) by Johann Sebastian Bach

### PR DESCRIPTION
**Pull request by jonathan-scholbach**
When issue #803 will be solved, I will add annotations and a translation in a .tex file, but I think the music sheet itself is worth being published at this stage.

### CODE REVIEW

**Comment by dominicus** [comment]
[Source edition](http://www.efkalmus.com/kalorchdetail.php?r=372) may not be in the public domain.
Is it possible adapting the code to an alternative PD source (i.e. Bach-Gesellschaft)?

**Comment by jonathan-scholbach** [comment]
I am not very familiar with the details of the law, but I believe an urtext edition is in public domain 25 years after publication of the edition, isn't it? At least this is the case in germany (§70 UrHG), where the source was published.

**Comment by jonathan-scholbach** [comment]
Just to substantiate the previously said: [The edition (Neue Bach-Ausgabe, New Bach Edition)](https://en.wikipedia.org/wiki/New_Bach_Edition) is a historical-critical edition and thus - imho - qualifies as a scientific edition in terms of [§70 UrhG](https://dejure.org/gesetze/UrhG/70.html), which sais that the copyright of the edition expires 25 years after the publication of the edition.

**Comment by dominicus** [comment]
General info on out-of-copyright requirements are in the [Contribute](http://www.mutopiaproject.org/contribute.html#typeset) page.  There's also additional references at the [wiki](https://github.com/MutopiaProject/MutopiaProject/wiki/FAQs%3A-Typesetting-public-domain-scores).
Mutopia content is made available for free download/use irrespective of user's location, thus strives to ensure content is in the public domain worldwide.
I'll restate our interest in getting your typesetting work on this piece featured in Mutopia, and offer my help adapting the LilyPond source to an available PD edition.

**Comment by jonathan-scholbach** [comment]
OK, I didn't expect that copyright could depend on the user's country. I thought, it would only depend on the publisher's country. So, we need to rework that. It's a strange situation - we have to add the mistakes of an older edition, don't we? Or can we just create a new edition, by changing some other things - for instance the breaks and some other stuff? I already adapted the orthography of the lyrics to contemporary german, added nummeration of the parts and changed two errata. I think there are some inconcsistencies in the slurring of Ameln, we can correct as well. Would that qualify as a "new" edition?
If that's not the case, I appreciate your offer of help very much! Which edition do we want to use and how do we want to share the workload?

**Comment by glenl** [comment]
**Caution**: your request for a pull is from your master and not a topic branch. This will work fine if nothing else is pushed to your master (that you don't want in this pull request) until after this pull request is processed. It is recommended that pull requests are made from branches. There should be a wiki article on this.

**Suggestion**: Since you have several source LilyPond files, they will be presented as a zipped collection of files. LateX sources and build instructions can be included in this zip archive as well.

**Comment by jonathan-scholbach** [comment]
@glenl Thanks, that came right in the moment before I actually would have pushed something else to my master.

**Comment by dominicus** [comment]
Corrections and readability improvements vs. the source are certainly welcome.  Read this [FAQ topic](https://github.com/MutopiaProject/MutopiaProject/wiki/FAQs:-Typesetting-public-domain-scores#do-i-need-to-match-the-source--may-i-implement-changes-to-the-music-i-typeset).

I haven't compiled your source to review the output vs. PD versions available, but here's a suggested high-level plan:

1. Compare current source output against available PD versions...select the one most closely aligned with respect to music notation.  Decide if this is appropriate as primary source.
2. Where it deviates, decide what to do with the deviation:

- Minor corrections and updates found in alternative PD source, OK to incorporate the change.  It helps to add comments to the code flagging the update and the alternate source.  These comments serve as future reference, and help us answer questions from end-users.
- Obvious flaws in typesetting or imaging in the primary source need not be supported by alternate PD.
- Implementing equivalent modern symbols for pedaling, articulations, tuplets, as well as spacing, page breaks, formatting...this is all at the discretion of the typesetter.
- Else, consider dropping the variation as likely copyrighted.

Please contact me directly javier (at) ruiz-alma (dot) com to discuss how we can collaborate on your project.

**Comment by glenl** [comment]
It occurred to me when commenting on #806 that you may experience problems with synchronizing with the Mutopia master branch after this pull is processed. To move these into a branch you need a little GIT surgery to remove the files from *master* and add them to a new branch.
```bash
$ git checkout master
$ git reset --soft HEAD~1
$ git status # should show 13 files in "changes not committed"
$ git checkout -b jesu-meine-freude
$ git commit -a
```
This should put the 13 files into the new branch. You would need to use ``--force`` in the push since you have pushed this to a public repository (assuming *origin* is the name of the remote):
```bash
$ git push --force origin jesu-meine-freude
```
This effectively moves the files from *master* to *jesu-meine-freude* so you will have to re-create the pull request.

**Comment by dominicus** [comment]
Closing this PR.  Piece to be submitted in a new pull request.

**Pull request closed without merging**
