### PR TITLE
New piece: Mozart KV 488, Allegro, all instruments

### PR DESCRIPTION
**Pull request by wchargin**
This pull request includes the first movement of Mozart’s Piano Concerto
№ 23 in A major (KV 488/KV488/K488), for all instruments.

The subtree `ftp/MozartWA/KV488/Mozart-KV488/Mozart-KV488-lys/` includes
a Makefile, whose `test` target verifies that all entry points compile
cleanly (no errors or warnings) with paper sizes both A4 and Letter.
A bare `make`, or `make all`, will build all outputs.

Every commit in this history compiles cleanly under `make test`. You can
run `make test MAKE='make -j4'` for approximately linear CPU-bound
speedup.

The source is a manuscript of Breitkopf and Härtel from 1879, available
on IMSLP: <https://imslp.org/wiki/Special:ReverseLookup/25720>
The PDF version of the source has the following SHA-256 hash:

    dd642c79649d00758dfa65c3dbc605d940edb1d14b2f53312282acb7a8a0fe9a

I’ve hand-checked each measure of the final score against the source,
and also listened to the rendered MIDI output.

Maintainers: please `merge --no-ff` this branch as-is; please *do not*
squash the history. Feel free to push any administrative commits (ID
changes, etc.) on top of the existing history; I’ve granted maintainer
permission to push to `wchargin/kv488-allegro`.

### CODE REVIEW

**Comment by wchargin** [comment]
cc @glenl: mind taking a look?

**Comment by glenl** [comment]
I pulled this into a local branch and built it yesterday. You've developed an efficient work space for a large project and I had no problem building. Here are the issues we have to address,

 * Naming convention --- submissions with multiple source files like yours need a slightly deeper folder hierarchy (see [our wiki page on this](https://github.com/MutopiaProject/MutopiaProject/wiki/Guidelines-for-new-score-submissions-using-github) and below).
* There should be a main LilyPond file (conductor score?) that needs to be named to match the folder hierarchy. It is this file that will be used to create the preview image on the site.
 * The part scores need to be in a separate folder. Our build script will individually build each LilyPond  file in the parts folder, and zip collect them into compressed `zip` and `tar.gz` archives.
 * I still have to figure out the midi bits.

This layout would work (leaving most of your file naming intact),
```bash
# in new folder, ftp/MozartWA/KV488/Mozart-KV488/Mozart-KV488-lys/
MozartWA-KV488.ly # renamed from MozartWA-KV488-conductor.ly
mutopia-header.ily  # this can be in common if you wish
common/
01_allegro/
02_andante/
03_presto/
# other shell scripts, Makefiles, etc.
parts/MozartWA-KV488-movement-*.ly
parts/MozartWA-KV488-part-*.ly
```

We won't use your Makefile and shell scripts. Our build script will compile the main score and all parts for both letter and A4 page sizes, build necessary archives, preview image, and create a static RDF file for the site.

**Comment by wchargin** [comment]
@glenl: Thank you for taking a look!

I am happy to reorganize the project as you suggest. We might want to
make a TODO to similarly update the structure of the “ensemble” template
in this repository—the directory structure is copied directly from that
template, so I had assumed that it was correct.

> We won't use your Makefile and shell scripts. Our build script will
> compile the main score and all parts for both letter and A4 page
> sizes, build necessary archives, preview image, and create a static
> RDF file for the site.

That’s fine with me. Is it okay with you if we retain the Makefile and
scripts in the repository, for the benefit of anyone else who should
want to work on the score? Or do you want me to remove them entirely?
I’ll certainly continue to use them myself as I work through the next
two movements, but I suppose that I _could_ add them to my
`.git/exclude` and use them only locally… it seems like a waste, though.

Thanks again! I’ll make these changes some time in the next few days and
get back to you.

**Comment by glenl** [comment]
You should keep all the scripts and support files you need to develop your piece. Scripts and Makefiles don't get published onto the website but they should remain in the archive for further development with the piece.

The ensemble template passed completely out of my brain! It probably needs more instructions in the readme.md file and more details about how to match the naming structure with regards to the `-lys` folder. The `parts-folder` is a relatively new thing that makes our build scripting easier. I may modify our build script to make some presumptions based on the naming in the ensemble template since I can't think of why `piece-part-x.ly` wouldn't be `part-x` of the piece. Same with midi.

I'm not used to contributors following our templates so well :grimacing:.

**Comment by wchargin** [comment]
Great; thanks!

I’ve updated the directory structure as you specified, treating the MIDI
entry points just like the other entry points.

**Comment by wchargin** [comment]
@glenl: friendly ping :-)

**Pull request closed without merging**
