### PR TITLE
Prep 885

### PR DESCRIPTION
**Pull request by glenl**
Closes #885

### CODE REVIEW

**Comment by chrissawer** [comment]
I don't seem to get any MIDI output when compiling Symphony5_2.
Would it be possible to fix this?

**Comment by glenl** [comment]
Fixed. Pull request had 2 pieces and I missed the second. I've updated the headers and fixed the midi issue.

**Comment by chrissawer** [comment]
@glenl thanks for looking but I don't see any more commits on the branch - could you double check if your latest fixes need pushing?

**Comment by glenl** [comment]
I mistakenly created this branch in the main upstream repository instead of my origin; then pushed my changes to origin and not upstream. Changes are there now (39ce583). I'll delete this errant branch after the merge. I knew this would goof me up at some point!

**Pull request merged**
