### PR TITLE
Fix 1

### PR DESCRIPTION
**Pull request by DanGrayson**
fix some spelling and punctuation (too many periods)

### CODE REVIEW

**Comment by DanGrayson** [comment]
Should I also convert the syntax to the latest version of lilypond?  If so, to the latest "stable" version or the latest "development" version?

**Comment by glenl** [comment]
Updating to the latest stable release is always safe.

If you prefer a newer release, a good approach is to convert-ly to 2.18.2, review & commit, then try your preferred release.

**Comment by DanGrayson** [comment]
Your advice seems directed at my personal use.  What version do you prefer the lilypond source files in this repository to be compatible with?  Let me know, and I'll update the file this pull request handles.

**Comment by glenl** [comment]
Update to the latest stable release --- 2.18.2.

**Comment by DanGrayson** [comment]
Thanks, will do.

**Comment by DanGrayson** [comment]
Okay, I've brought the score up to date with lilypond, made it fit into 4 pages, stopped it from making midi files, and fixed an error (see commit dfc790f791027ee1fdf63f646fc92634350f686d for details).

This is ready to review.

**Comment by glenl** [comment]
Midi is needed for publication so I'll add that back in (see https://github.com/MutopiaProject/MutopiaProject/pull/1048/commits/406929bd83e5dd0a065e25322c90e59872ddbb2c) as I update the tag and copyright markup.

I find this very readable at 4 pages, The downside is some beaming isn't allowed to spread and you end up with a note adjacent to the beam --- I noticed this while reviewing bar 52. I understand this is a compromise and if you are satisfied with the readability, just let me know here and I'll submit this for publication with only the midi addition.

Thanks for the contribution!

**Comment by DanGrayson** [comment]
Getting it down to 4 pages seems useful to me, since then the whole piece can be displayed on the piano.

Yes, the location of the beam in bar 52 is annoying, and there is a warning message about it.  I'd be happy to fix it, if anyone knows a way.
```
liszt-consolation-no3.ly:230:14: warning: no viable initial configuration found: may not find good beam slope
    d,\rest f
             [_\( des' ces aes' des, ces f, des' ces aes' \change Staff="up"
```

Screen Shot 2019-05-30 at 3 11 00 PM

So, I'm not really satisfied, but perhaps this is good enough for now.

**Comment by DanGrayson** [comment]
Actually, the beam position is something lilypond should manage on its own, for in this situation, it's clear what ought to be done.  I could report that as an issue to lilypond.

**Comment by glenl** [comment]
Using ```\override Beam.positions #'(7 . 7)``` raised the beam just enough to look better and clear the message. I've merged this into a publication branch (#1052) for Chris.

**Pull request closed without merging**
